# -*- coding: utf-8 -*-
"""datacsv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xrrE7y3czDzNESRIWjaUxPg5MiSeTj6u
"""

import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[2] not in a:
            a.append(row[2])
print(a)

def age():
    a=['37', '46', '50', '78', '75', '23', '67', '52', '68', '43', '47', '25', '58', '32', '39', '72', '79', '26', '30', '22', '34', '42', '64', '48', '28', '33', '31', '60', '69', '20', '57', '19', '38', '54', '35', '51', '66', '61', '24', '55', '59', '71', '49', '40', '21', '45', '29', '62', '76', '77', '73', '41', '56', '80', '63', '53', '44', '70', '74', '36', '27', '65']
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            for i in a:
                if row[2] == i:
                    with open('age.csv', 'a', newline='') as file:
                        writer = csv.writer(file, delimiter=',')
                        writer.writerow((row[0], row[1], "1", i))
age()

import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[4] not in a:
            a.append(row[4])
print(a)



def num_of_dependents():
    a=['0', '3', '1', '2', '4', '6', '5', '9', '7', '8']
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            for i in a:
                if row[4] == i:
                    with open('num_of_dependents.csv', 'a', newline='') as file:
                        writer = csv.writer(file, delimiter=',')
                        writer.writerow((row[0], row[1], "2", i))
num_of_dependents()

['Avg Monthly Long Distance Charges',
 'Avg Monthly GB Download', 
 'Monthly Charge', 
 'Total Charges',
 'Total Refunds', 
 'Total Long Distance Charges', 
 'Total Revenue']

import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[13] not in a:
            a.append(row[13])
print(a)



def avg_monthly_long_dis_charges():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[13] not in a:
                a.append(row[13])
    for i in a:
        if '' in a:
            a.remove('')
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            for i in a:
                if row[13] == i:
                    with open('avg_monthly_long_dis_charges2.csv', 'a', newline='') as file:
                        writer = csv.writer(file, delimiter=',')
                        writer.writerow((row[0], row[1], "1", i))
avg_monthly_long_dis_charges()

import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[17] not in a:
            a.append(row[17])
print(a)

def avg_monthly_gb_download():
    with open('telecomdata.csv','r') as file:
            reader = csv.reader(file)
            a = []
            for row in reader:
                if row[17] not in a:
                    a.append(row[17])
    for i in a:
            if '' in a:
                a.remove('')
    with open('telecomdata.csv', 'r') as file:
            reader = csv.reader(file)
            for row in reader:
                for i in a:
                    if row[17] == i:
                        with open('avg_monthly_gb_download2.csv', 'a', newline='') as file:
                            writer = csv.writer(file, delimiter=',')
                            writer.writerow((row[0], row[1], "2", i))
avg_monthly_gb_download()

import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[29] not in a:
            a.append(row[29])
print(a)



def monthly_charge():
    with open('telecomdata.csv','r') as file:
          reader = csv.reader(file)
          a = []
          for row in reader:
              if row[29] not in a:
                  a.append(row[29])
    for i in a:
          if '' in a:
              a.remove('')
      
    with open('telecomdata.csv', 'r') as file:
          reader = csv.reader(file)
          for row in reader:
              for i in a:
                  if row[29] == i:
                      with open('monthly_charge2.csv', 'a', newline='') as file:
                          writer = csv.writer(file, delimiter=',')
                          writer.writerow((row[0], row[1], "2", i))
monthly_charge()



import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[30] not in a:
            a.append(row[30])
print(a)



import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[31] not in a:
            a.append(row[31])
print(a)

def total_charges():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[30] not in a:
                a.append(row[30])
    for i in a:
        if '' in a:
            a.remove('')
    

    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            for i in a:
                if row[30] == i:
                    with open('total_charges2.csv', 'a', newline='') as file:
                        writer = csv.writer(file, delimiter=',')
                        writer.writerow((row[0], row[1], "3", i))
total_charges()



import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[31] not in a:
            a.append(row[31])
print(a)

def total_refunds():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[31] not in a:
                a.append(row[31])
    for i in a:
        if '' in a:
            a.remove('')
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            for i in a:
                if row[31] == i:
                    with open('total_refunds2.csv', 'a', newline='') as file:
                        writer = csv.writer(file, delimiter=',')
                        writer.writerow((row[0], row[1], "4", i))
total_refunds()

import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[33] not in a:
            a.append(row[33])
print(a)



def total_long_dist_charges():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[33] not in a:
                a.append(row[33])
    for i in a:
        if '' in a:
            a.remove('')
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            for i in a:
                if row[33] == i:
                    with open('total_long_dist_charges2.csv', 'a', newline='') as file:
                        writer = csv.writer(file, delimiter=',')
                        writer.writerow((row[0], row[1], "5", i))
total_long_dist_charges()



import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[34] not in a:
            a.append(row[34])
print(a)

def total_revenue():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[34] not in a:
                a.append(row[34])
    for i in a:
        if '' in a:
            a.remove('')
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            for i in a:
                if row[34] == i:
                    with open('total_revenue2.csv', 'a', newline='') as file:
                        writer = csv.writer(file, delimiter=',')
                        writer.writerow((row[0], row[1], "6", i))
total_revenue()

"""float bitti

"""



import csv

with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[22] not in a:
            a.append(row[22])
print(a)



def streaming_tv():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[22] not in a:
                a.append(row[22])
    for i in a:
        if '' in a:
            a.remove('')
            
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            with open('streaming_tv2.csv', 'a', newline='') as file:
                if row[22] == "Yes":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "11", "Y"))
                elif row[22] == "No":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "11", "N"))
streaming_tv()



import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[23] not in a:
            a.append(row[23])
print(a)



def streaming_movies():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[23] not in a:
                a.append(row[23])
    for i in a:
        if '' in a:
            a.remove('')
    
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            with open('streaming_movies.csv', 'a', newline='') as file:
                if row[23] == "Yes":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "12", "Y"))
                elif row[23] == "No":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "12", "N"))
streaming_movies()

import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[24] not in a:
            a.append(row[24])
print(a)

def streaming_music():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[24] not in a:
                a.append(row[24])
    for i in a:
        if '' in a:
            a.remove('')
    
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            with open('streaming_music.csv', 'a', newline='') as file:
                if row[24] == "Yes":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "13", "Y"))
                elif row[24] == "No":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "13", "N"))
streaming_music()

import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[25] not in a:
            a.append(row[25])
print(a)

def unlimited_data():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[25] not in a:
                a.append(row[25])
    for i in a:
        if '' in a:
            a.remove('')
    
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            with open('unlimited_data.csv', 'a', newline='') as file:
                if row[25] == "Yes":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "14", "Y"))
                elif row[25] == "No":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "14", "N"))
unlimited_data()



import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[27] not in a:
            a.append(row[27])
print(a)



def paperless():
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            with open('paperless_billing.csv', 'a', newline='') as file:
                if row[27] == "Yes":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "10", "Y"))
                elif row[27] == "No":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "10", "N"))
paperless()



import csv
with open('telecomdata.csv','r') as file:
    reader = csv.reader(file)
    a = []
    for row in reader:
        if row[14] not in a:
            a.append(row[14])
print(a)



def multiple_lines():
    with open('telecomdata.csv','r') as file:
        reader = csv.reader(file)
        a = []
        for row in reader:
            if row[14] not in a:
                a.append(row[14])
    for i in a:
        if '' in a:
            a.remove('')
    
    with open('telecomdata.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            with open('multiple_lines2.csv', 'a', newline='') as file:
                if row[14] == "Yes":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "9", "Y"))
                elif row[14] == "No":
                    writer = csv.writer(file, delimiter=',')
                    writer.writerow((row[0], row[1], "9", "N"))
multiple_lines()

